name: Setup WireGuard VPN

on:
  push:
    branches:
      - main

jobs:
  setup-vpn:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wireguard qrencode

    - name: Generate keys and configs without here-doc
      run: |
        wg genkey | tee privatekey | wg pubkey > publickey
        PRIVATE_KEY=$(cat privatekey)
        PUBLIC_KEY=$(cat publickey)
        CLIENT_PRIV_KEY=$(wg genkey)
        CLIENT_PUB_KEY=$(echo $CLIENT_PRIV_KEY | wg pubkey)
        SERVER_IP="10.0.0.1/24"
        CLIENT_IP="10.0.0.2/32"
        ENDPOINT="vpn.example.com:51820"

        # Создаём серверный конфиг
        printf "[Interface]\nPrivateKey = %s\nAddress = %s\nListenPort = 51820\n\n[Peer]\nPublicKey = %s\nAllowedIPs = %s\n" \
          "$PRIVATE_KEY" "$SERVER_IP" "$CLIENT_PUB_KEY" "$CLIENT_IP" > wg0.conf

        # Создаём клиентский конфиг
        printf "[Interface]\nPrivateKey = %s\nAddress = %s\nDNS = 1.1.1.1\n\n[Peer]\nPublicKey = %s\nEndpoint = %s\nAllowedIPs = 0.0.0.0/0\nPersistentKeepalive = 25\n" \
          "$CLIENT_PRIV_KEY" "$CLIENT_IP" "$PUBLIC_KEY" "$ENDPOINT" > client.conf

        # Создаём QR-код из клиентского конфига
        qrencode -o client.png < client.conf

    - name: Check client config and QR code files
      run: |
        echo "Listing current directory files:"
        ls -l
        echo "Checking specific files:"
        ls -l client.conf client.png || echo "Files not found!"

    - name: Upload client config and QR code
      uses: actions/upload-artifact@v4
      with:
        name: wireguard-client-files
        path: |
          client.conf
          client.png
