name: Setup WireGuard VPN

on:
  workflow_dispatch:

jobs:
  setup-vpn:
    runs-on: ubuntu-latest
    steps:
    - name: Setup WireGuard server and generate config
      run: |
        sudo apt update
        sudo apt install -y wireguard qrencode
        wg genkey | tee privatekey | wg pubkey > publickey
        PRIVATE_KEY=$(cat privatekey)
        PUBLIC_KEY=$(cat publickey)
        CLIENT_PRIV_KEY=$(wg genkey)
        CLIENT_PUB_KEY=$(echo $CLIENT_PRIV_KEY | wg pubkey)
        SERVER_IP="10.0.0.1/24"
        CLIENT_IP="10.0.0.2/32"
        ENDPOINT="vpn.example.com:51820"

        cat > wg0.conf << EOF
        [Interface]
        PrivateKey = $PRIVATE_KEY
        Address = $SERVER_IP
        ListenPort = 51820

        [Peer]
        PublicKey = $CLIENT_PUB_KEY
        AllowedIPs = $CLIENT_IP
        EOF

        cat > client.conf << EOF
        [Interface]
        PrivateKey = $CLIENT_PRIV_KEY
        Address = $CLIENT_IP
        DNS = 1.1.1.1

        [Peer]
        PublicKey = $PUBLIC_KEY_
